### ISSUE TITLE
FYI: backslashes AND forward slash

### ISSUE THREAD

**Issue by jaysnoddy** [jtojnar/markdown-image-insertion#2]
I really like this!
But one minor problem. 
I left checked the the "Replace backslashes..." option, I get *both* types of slashes.
        ../..\assets\imgname.jpeg 
I am using Windows 10.

**Comment by jaysnoddy** [comment]
BTW, and unrelated to this minor issue...in case you like to know how people use your stuff, perhaps you might like to know a complicated use-case it supports.  (also, note this slash problem happened BEFORE I tried this complicated use).  I use it to produce the following code blocks for latex and html export. (I just need to copy the url to the HTML)  it generates
~~~~
~~~{=html}
<figure>
 <img src=" URL " alt="Photo|Chart|etc ALT "/>
 <figcaption>CAPTION  Credits:
</figcaption>
</figure>
~~~
~~~~

~~~~
~~~{=latex}
\begin{figure} \centering  \includegraphics[width=0.95\textwidth]../..\assets\ecolisemlarge.jpeg
\caption{CAPTION
\\  \footnotesize
Credits:  
\normalsize }
\end{figure}
~~~
 ~~~~

**Comment by jtojnar** [comment]
Thanks for reporting. I vaguely recall having this same issue back when I still used this but I could not see the pattern.

Apparently, the [`replace` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) only replaces the first instance.

Fixed the issue in https://github.com/jtojnar/markdown-image-insertion/commit/778241949e6fc24ec724a9fa3759acf96f5809ae

**Comment by jtojnar** [comment]
For your use case, do you switch between two different values of `markdown-image-insertion.general.imageCode` setting, or just set it to `{url} and create the surrounding code manually?

Something like #3 might be useful.

**Comment by jtojnar** [comment]
Published a new release: https://github.com/jtojnar/markdown-image-insertion/releases/tag/v0.2.2

**Comment by jaysnoddy** [comment]
for my use case, multiple options for outputs would be nice! (but not essential) 
also, the ability to select two options at same time would be good (e.g. export a html block and a latex block at same time), but again not essential. 
(currently I just copy the url into the html block, when adding captions, etc.)
